services:
  db:
    image: postgres:13
    container_name: medusa-db
    restart: always
    environment:
      POSTGRES_USER: medusa_user
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: medusa_dev
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  medusa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medusa-app
    env_file: MEDUSA_LOCAL.env
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata:
    driver: local

