services:
  db:
    image: postgres:13
    container_name: medusa-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: medusa_user
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: medusa_dev
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  medusa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medusa
    restart: on-failure
    env_file: .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - medusa-net

volumes:
  db_data:

networks:
  medusa-net:
    driver: bridge

