services:
  postgres:
    image: postgres:13
    container_name: medusa-postgres
    restart: always
    environment:
      POSTGRES_USER: medusa_user
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: medusa_dev
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  redis:
    image: redis:8.0
    container_name: medusa-redis
    restart: always
    environment:
      REDIS_PASSWORD: mysecretpassword
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  medusa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medusa-app
    env_file: MEDUSA_LOCAL.env
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"

volumes:
  pgdata:
  redis_data:
  air-cache:

